-- ========================================================
-- KORUNA ACADEMY - PHASE 1: 4 USER ROLES & PROFILES SCHEMA
-- Roles: 'employee', 'team_leader', 'trainer', 'admin'
-- Paste into Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
-- ========================================================

-- 1. Create Profiles Table with Role Enforcement
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  user_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'employee' CHECK (role IN ('employee', 'team_leader', 'trainer', 'admin')),
  department TEXT DEFAULT 'Software Engineering',
  email TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure user_id column exists for existing instances
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS user_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Define RLS Policies for Profiles
-- Drop policies if they exist to allow clean re-runs
DROP POLICY IF EXISTS "Profiles read access" ON public.profiles;
DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users delete profile" ON public.profiles;

-- Read Access: Authenticated users can view profiles
CREATE POLICY "Profiles read access" ON public.profiles FOR SELECT USING (true);

-- Update Access: Users can update their own profile, Admins can update any profile
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Insert Access: Users can insert their own profile
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Delete Access: Enable profiles delete
CREATE POLICY "Users delete profile" ON public.profiles FOR DELETE USING (true);

-- 4. Trigger to automatically create a Profile when a User signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, department, role, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'department', 'Software Engineering'),
    COALESCE(NEW.raw_user_meta_data->>'role', 'employee'),
    NEW.email
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    department = EXCLUDED.department,
    role = EXCLUDED.role,
    email = EXCLUDED.email;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists to allow clean re-runs
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ========================================================
-- KORUNA ACADEMY - PHASE 2: COURSES, PROGRESS & PRACTICALS
-- ========================================================

-- 5. Create Courses Table
CREATE TABLE IF NOT EXISTS public.courses (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  rating NUMERIC DEFAULT 4.5,
  code TEXT NOT NULL UNIQUE,
  level TEXT CHECK (level IN ('Beginner', 'Intermediate', 'Advanced')),
  description TEXT,
  img_bg TEXT,
  lessons JSONB DEFAULT '[]'::jsonb,
  quiz JSONB DEFAULT '[]'::jsonb,
  assigned_users JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure assigned_users column exists for existing database instances
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS assigned_users JSONB DEFAULT '[]'::jsonb;

-- Enable RLS for courses
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- RLS Policies for courses
DROP POLICY IF EXISTS "Allow public read access to courses" ON public.courses;
DROP POLICY IF EXISTS "Allow trainers and admins to insert courses" ON public.courses;
DROP POLICY IF EXISTS "Allow trainers and admins to update courses" ON public.courses;
DROP POLICY IF EXISTS "Allow trainers and admins to delete courses" ON public.courses;

CREATE POLICY "Allow public read access to courses" ON public.courses FOR SELECT USING (true);
CREATE POLICY "Allow trainers and admins to insert courses" ON public.courses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow trainers and admins to update courses" ON public.courses FOR UPDATE USING (true);
CREATE POLICY "Allow trainers and admins to delete courses" ON public.courses FOR DELETE USING (true);

-- 6. Create User Progress Table
CREATE TABLE IF NOT EXISTS public.user_progress (
  user_email TEXT NOT NULL,
  course_id TEXT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  application_id INTEGER DEFAULT 0,
  progress_percent INTEGER DEFAULT 0,
  completed_lessons JSONB DEFAULT '[]'::jsonb,
  quiz_score INTEGER,
  quiz_attempts INTEGER DEFAULT 0,
  practical_status TEXT DEFAULT 'none' CHECK (practical_status IN ('none', 'pending', 'approved', 'rejected')),
  practical_notes TEXT,
  overdue BOOLEAN DEFAULT false,
  due_date TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (user_email, course_id, application_id)
);

-- Ensure application_id column exists for existing instances
ALTER TABLE public.user_progress ADD COLUMN IF NOT EXISTS application_id INTEGER DEFAULT 0;

-- Enable RLS for user progress
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user progress
DROP POLICY IF EXISTS "Allow read access to user progress" ON public.user_progress;
DROP POLICY IF EXISTS "Allow insert to user progress" ON public.user_progress;
DROP POLICY IF EXISTS "Allow update to user progress" ON public.user_progress;
DROP POLICY IF EXISTS "Allow delete to user progress" ON public.user_progress;

CREATE POLICY "Allow read access to user progress" ON public.user_progress FOR SELECT USING (true);
CREATE POLICY "Allow insert to user progress" ON public.user_progress FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update to user progress" ON public.user_progress FOR UPDATE USING (true);
CREATE POLICY "Allow delete to user progress" ON public.user_progress FOR DELETE USING (true);

-- 7. Create Practical Submissions Table
CREATE TABLE IF NOT EXISTS public.practical_submissions (
  id TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  user_name TEXT NOT NULL,
  course_id TEXT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  course_title TEXT NOT NULL,
  submission_text TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  date_submitted TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for practical submissions
ALTER TABLE public.practical_submissions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for practical submissions
DROP POLICY IF EXISTS "Allow read access to practical submissions" ON public.practical_submissions;
DROP POLICY IF EXISTS "Allow insert to practical submissions" ON public.practical_submissions;
DROP POLICY IF EXISTS "Allow update to practical submissions" ON public.practical_submissions;

CREATE POLICY "Allow read access to practical submissions" ON public.practical_submissions FOR SELECT USING (true);
CREATE POLICY "Allow insert to practical submissions" ON public.practical_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update to practical submissions" ON public.practical_submissions FOR UPDATE USING (true);

-- Drop the legacy course_assignments table if it was previously created
DROP TABLE IF EXISTS public.course_assignments CASCADE;

-- 8. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
  id TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  course_id TEXT REFERENCES public.courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'other',
  is_read BOOLEAN DEFAULT false,
  assigned_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist to allow clean re-runs
DROP POLICY IF EXISTS "Allow read access to notifications" ON public.notifications;
DROP POLICY IF EXISTS "Allow insert to notifications" ON public.notifications;
DROP POLICY IF EXISTS "Allow update to notifications" ON public.notifications;
DROP POLICY IF EXISTS "Allow delete to notifications" ON public.notifications;

-- RLS Policies for notifications
CREATE POLICY "Allow read access to notifications" ON public.notifications FOR SELECT USING (true);
CREATE POLICY "Allow insert to notifications" ON public.notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update to notifications" ON public.notifications FOR UPDATE USING (true);
CREATE POLICY "Allow delete to notifications" ON public.notifications FOR DELETE USING (true);

